//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyInc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9ba3a372-1892-4ec7-b710-3e6b8008a4ab")]
        public string SweetsOrderConsultantId {
            get {
                return ((string)(this["SweetsOrderConsultantId"]));
            }
            set {
                this["SweetsOrderConsultantId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("efbef2bd3bf642d2a371e49127091535")]
        public string SweetsOrderConsultantSubscriptionKey {
            get {
                return ((string)(this["SweetsOrderConsultantSubscriptionKey"]));
            }
            set {
                this["SweetsOrderConsultantSubscriptionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c5a93c2e-c6be-4c80-997c-29453e8599e8")]
        public string PartyOrganizerId {
            get {
                return ((string)(this["PartyOrganizerId"]));
            }
            set {
                this["PartyOrganizerId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03df50f3cde84da9a799ae6516dfc21e")]
        public string PartyOrganizerSubscriptionKey {
            get {
                return ((string)(this["PartyOrganizerSubscriptionKey"]));
            }
            set {
                this["PartyOrganizerSubscriptionKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("d2c55d8d-6774-407a-925b-22c4769daeff")]
        public string DrinksOrderConsultantId {
            get {
                return ((string)(this["DrinksOrderConsultantId"]));
            }
            set {
                this["DrinksOrderConsultantId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5f2333f63aa34e96a9a6cd72ead5ff61")]
        public string DrinksOrderConsultantSubscriptionKey {
            get {
                return ((string)(this["DrinksOrderConsultantSubscriptionKey"]));
            }
            set {
                this["DrinksOrderConsultantSubscriptionKey"] = value;
            }
        }
    }
}
